### ISSUE TITLE
Actividad 5 cuadro comparativo

### ISSUE THREAD

**Issue by Vanessacruzortiz** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-Vanessacruzortiz#1]
Actividad 5 cuadro comparativo TIPOS DE TEXTO
Vanessa Cruz Ortiz 1BS
[ACTIVIDAD 5 CUADRO COMPARATIVO DE TEXTOS VANESSA CRUZ ORTIZ.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-Vanessacruzortiz/files/9641551/ACTIVIDAD.5.CUADRO.COMPARATIVO.DE.TEXTOS.VANESSA.CRUZ.ORTIZ.pdf)

**Comment by Blanca-estela-valerio-rivero** [comment]
De acuerdo a la rúbrica tiene un 17% de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
